# Generated by Django 5.0.3 on 2024-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0014_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
